<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class EnhancedQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ===== ÁRBITROS - FÁCIL =====
            [
                'question_code' => 'ARB-F-001',
                'title' => 'Falta personal - Definición básica',
                'description' => '¿Cuál es la definición correcta de una falta personal?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro', 'entrenador'],
                'difficulty' => 'baja',
                'option_a' => 'Un contacto ilegal entre jugadores',
                'option_b' => 'Un movimiento ilegal sin contacto',
                'option_c' => 'Un contacto ilegal entre un jugador defensivo y uno ofensivo',
                'option_d' => 'Solo un contacto durante el lanzamiento',
                'correct_answer' => 'C',
                'explanation' => 'Una falta personal es el contacto ilegal entre un jugador defensivo y uno ofensivo, o entre jugadores cuando no hay balón. Cualquier contacto que interfiera con el movimiento es una falta. Art. 35 Reglamento FEB.',
                'reference' => 'Art. 35 - Falta Personal',
                'image_path' => null,
            ],
            [
                'question_code' => 'ARB-F-002',
                'title' => '¿Cuántas faltas descalifica a un jugador?',
                'description' => '¿Después de cuántas faltas personales un jugador es descalificado?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro', 'entrenador'],
                'difficulty' => 'baja',
                'option_a' => 'Después de 3 faltas',
                'option_b' => 'Después de 4 faltas',
                'option_c' => 'Después de 5 faltas',
                'option_d' => 'Después de 6 faltas',
                'correct_answer' => 'C',
                'explanation' => 'Un jugador es descalificado cuando comete su quinta falta personal. A esto se le llama "eliminación" o "descalificación".',
                'reference' => 'Art. 35 - Falta Personal',
                'image_path' => null,
            ],
            [
                'question_code' => 'ARB-F-003',
                'title' => 'Regla de 24 segundos',
                'description' => '¿Cuál es el tiempo máximo que un equipo tiene para lanzar a canasta?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro', 'entrenador', 'oficial'],
                'difficulty' => 'baja',
                'option_a' => '20 segundos',
                'option_b' => '24 segundos',
                'option_c' => '30 segundos',
                'option_d' => '35 segundos',
                'correct_answer' => 'B',
                'explanation' => 'La regla de 24 segundos establece que un equipo debe lanzar a canasta dentro de 24 segundos desde que obtiene la posesión del balón. Art. 29 Reglamento FEB.',
                'reference' => 'Art. 29 - Regla de 24 segundos',
                'image_path' => null,
            ],

            // ===== ÁRBITROS - INTERMEDIO =====
            [
                'question_code' => 'ARB-M-001',
                'title' => 'Regla de los 3 segundos en zona',
                'description' => '¿Un jugador ofensivo puede estar más de 3 segundos en la zona restringida?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro', 'entrenador'],
                'difficulty' => 'media',
                'option_a' => 'Sí, sin límite de tiempo',
                'option_b' => 'No, debe salir inmediatamente',
                'option_c' => 'Sí, mientras su equipo tenga el balón puede estar más de 3 segundos',
                'option_d' => 'Solo puede estar 2 segundos',
                'correct_answer' => 'C',
                'explanation' => 'Un jugador ofensivo puede estar en la zona restringida indefinidamente mientras su equipo tenga la posesión del balón. La regla de 3 segundos se aplica cuando el equipo está atacando y tiene posesión. Art. 26.3 Reglamento FEB.',
                'reference' => 'Art. 26.3 - Regla de 3 segundos',
                'image_path' => null,
            ],
            [
                'question_code' => 'ARB-M-002',
                'title' => 'Violación de campo atrás (retaguardia)',
                'description' => 'Un jugador cruza la línea de medio campo con el balón. ¿Es violación?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro', 'entrenador'],
                'difficulty' => 'media',
                'option_a' => 'Sí, siempre es violación',
                'option_b' => 'No, puede cruzar sin problema',
                'option_c' => 'Solo si toca el balón después de cruzar',
                'option_d' => 'Solo si el defensa está en retaguardia',
                'correct_answer' => 'B',
                'explanation' => 'No hay violación por cruzar la línea de medio campo. La violación de retaguardia ocurre cuando un jugador que estaba en retaguardia pisa el campo de ataque habiendo tocado el balón en retaguardia, o cuando el balón vuelve a retaguardia. Art. 30 Reglamento FEB.',
                'reference' => 'Art. 30 - Violación de retaguardia',
                'image_path' => null,
            ],
            [
                'question_code' => 'ARB-M-003',
                'title' => 'Pasos con pivote',
                'description' => 'Un jugador establece pivote y da dos pasos más un bote. ¿Es correcto?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro', 'entrenador'],
                'difficulty' => 'media',
                'option_a' => 'No, solo puede dar dos pasos en total',
                'option_b' => 'Sí, después de pivotar puede botar',
                'option_c' => 'No, si bota debe hacerlo antes del primer paso',
                'option_d' => 'Sí, sin límite de pasos si bota al final',
                'correct_answer' => 'B',
                'explanation' => 'Un jugador puede establecer un pie pivote, dar dos pasos y luego realizar un bote. El bote puede ocurrir después de los pasos. Art. 24.3 Reglamento FEB.',
                'reference' => 'Art. 24.3 - Pasos y pivote',
                'image_path' => null,
            ],

            // ===== ÁRBITROS - DIFÍCIL =====
            [
                'question_code' => 'ARB-D-001',
                'title' => 'Dobles - Control simultáneo',
                'description' => 'Un jugador bota el balón, lo controla con ambas manos simultáneamente y luego lo bota de nuevo. ¿Es una infracción?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro'],
                'difficulty' => 'alta',
                'option_a' => 'No, puede controlar el balón con ambas manos mientras lo bota',
                'option_b' => 'Sí, es un doble inmediato',
                'option_c' => 'Solo si lanza después',
                'option_d' => 'No, porque el contacto es simultáneo',
                'correct_answer' => 'B',
                'explanation' => 'Una vez que un jugador ha botado el balón, no puede volver a botarlo si previamente lo ha controlado con ambas manos simultáneamente. Esto constituye un doble. Art. 25.2 Reglamento FEB.',
                'reference' => 'Art. 25.2 - Dobles',
                'image_path' => null,
            ],
            [
                'question_code' => 'ARB-D-002',
                'title' => 'Falta antideportiva - Situación compleja',
                'description' => 'El jugador A8 realiza una entrada a canasta cuando quedan 2 segundos para el final. Después de lanzar, suena la señal de final y el jugador B2 golpea en la mano de A8. ¿Qué sucede?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro'],
                'difficulty' => 'alta',
                'option_a' => 'La canasta vale y el jugador A8 tendrá 1 tiro libre como consecuencia de la falta',
                'option_b' => 'La canasta no valdrá y el jugador tirará dos tiros libres',
                'option_c' => 'La canasta valdrá y la falta se ignorará porque está fuera de tiempo',
                'option_d' => 'El juego continúa sin sanción',
                'correct_answer' => 'C',
                'explanation' => 'Cuando suena la señal de final de cuarto, las faltas ocurridas después de ese momento no se sancionan. Si la canasta fue antes del sonido, cuenta. Art. 37 Reglamento FEB.',
                'reference' => 'Art. 37 - Final de cuarto',
                'image_path' => null,
            ],
            [
                'question_code' => 'ARB-D-003',
                'title' => 'Interferencia de balón - Trayectoria',
                'description' => 'Un defensor toca el balón cuando está en trayectoria descendente hacia la canasta, pero aún está subiendo. ¿Es interferencia?',
                'category' => 'arbitro',
                'applicable_roles' => ['arbitro'],
                'difficulty' => 'alta',
                'option_a' => 'Sí, es interferencia siempre',
                'option_b' => 'No, es un bloqueo permitido',
                'option_c' => 'No, porque el balón está subiendo',
                'option_d' => 'Sí, pero solo en tiros libres',
                'correct_answer' => 'C',
                'explanation' => 'La interferencia de balón en canasta solo ocurre cuando el balón está en trayectoria descendente hacia la canasta. Si el balón está en fase ascendente, es un bloqueo legal. Art. 31.2 Reglamento FEB.',
                'reference' => 'Art. 31.2 - Interferencia de balón',
                'image_path' => null,
            ],

            // ===== OFICIALES DE MESA - FÁCIL =====
            [
                'question_code' => 'OFI-F-001',
                'title' => 'Duración de un timeout',
                'description' => '¿Cuánto tiempo dura un tiempo muerto (timeout)?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial', 'entrenador'],
                'difficulty' => 'baja',
                'option_a' => '30 segundos',
                'option_b' => '60 segundos',
                'option_c' => '45 segundos',
                'option_d' => '90 segundos',
                'correct_answer' => 'B',
                'explanation' => 'Un tiempo muerto regular (timeout) dura 60 segundos según el Reglamento FEB. Art. 19 Reglamento FEB.',
                'reference' => 'Art. 19 - Tiempo Muerto',
                'image_path' => null,
            ],
            [
                'question_code' => 'OFI-F-002',
                'title' => 'Puntos de una canasta normal',
                'description' => '¿Cuántos puntos vale una canasta dentro de la línea de 3 puntos?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial', 'entrenador'],
                'difficulty' => 'baja',
                'option_a' => '1 punto',
                'option_b' => '2 puntos',
                'option_c' => '3 puntos',
                'option_d' => '4 puntos',
                'correct_answer' => 'B',
                'explanation' => 'Una canasta anotada dentro de la línea de 3 puntos vale 2 puntos. Una canasta de 3 puntos debe ser completamente fuera de esa línea.',
                'reference' => 'Art. 23 - Puntuación',
                'image_path' => null,
            ],
            [
                'question_code' => 'OFI-F-003',
                'title' => 'Registro de faltas personales',
                'description' => '¿Cuántas faltas personales tiene derecho a cometer un jugador?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial', 'entrenador'],
                'difficulty' => 'baja',
                'option_a' => '3 faltas',
                'option_b' => '4 faltas',
                'option_c' => '5 faltas',
                'option_d' => '6 faltas',
                'correct_answer' => 'C',
                'explanation' => 'Un jugador puede cometer hasta 5 faltas personales antes de ser descalificado. La 5ª falta resulta en su eliminación del juego. Art. 35 Reglamento FEB.',
                'reference' => 'Art. 35 - Falta Personal',
                'image_path' => null,
            ],

            // ===== OFICIALES DE MESA - INTERMEDIO =====
            [
                'question_code' => 'OFI-M-001',
                'title' => 'Faltas de equipo por período',
                'description' => 'En un período, un equipo comete 4 faltas personales. ¿Qué sucede?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial'],
                'difficulty' => 'media',
                'option_a' => 'Nada especial, se juega normalmente',
                'option_b' => 'La siguiente falta genera 2 tiros libres',
                'option_c' => 'El equipo es penalizado',
                'option_d' => 'Solo la 5ª falta genera tiros libres',
                'correct_answer' => 'B',
                'explanation' => 'Cuando un equipo comete 4 o más faltas en un período, cualquier falta adicional sancionada con tiros libres conlleva 2 tiros libres (excepto en faltas de 3 puntos). Art. 37 Reglamento FEB.',
                'reference' => 'Art. 37 - Faltas de equipo',
                'image_path' => null,
            ],
            [
                'question_code' => 'OFI-M-002',
                'title' => 'Regla de 24 segundos - Reset',
                'description' => 'Un equipo pierde la posesión por falta ofensiva. ¿Cómo se resetea el cronómetro?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial'],
                'difficulty' => 'media',
                'option_a' => 'Se resetea a 24 segundos para el nuevo equipo',
                'option_b' => 'Se resetea a 14 segundos',
                'option_c' => 'Continúa desde donde estaba',
                'option_d' => 'Se detiene indefinidamente',
                'correct_answer' => 'A',
                'explanation' => 'Cuando cambia la posesión, el cronómetro de 24 segundos se resetea a 24 segundos completos para el nuevo equipo en posesión. Art. 29.1 Reglamento FEB.',
                'reference' => 'Art. 29.1 - Regla de 24 segundos',
                'image_path' => null,
            ],
            [
                'question_code' => 'OFI-M-003',
                'title' => 'Canasta válida - Interferencia',
                'description' => 'El balón pasa a través del aro pero un jugador toca el aro antes de que salga. ¿Es canasta válida?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial'],
                'difficulty' => 'media',
                'option_a' => 'Sí, siempre que haya pasado el aro',
                'option_b' => 'No, es interferencia de balón',
                'option_c' => 'Sí, solo si el contacto es involuntario',
                'option_d' => 'Depende del árbitro',
                'correct_answer' => 'B',
                'explanation' => 'Si el balón ha pasado completamente a través de la canasta desde arriba y es tocado antes de salir, es interferencia de balón en canasta y no es válida. Art. 31.2 Reglamento FEB.',
                'reference' => 'Art. 31.2 - Interferencia de balón en canasta',
                'image_path' => null,
            ],

            // ===== OFICIALES DE MESA - DIFÍCIL =====
            [
                'question_code' => 'OFI-D-001',
                'title' => 'Timeouts por parte - Conteo avanzado',
                'description' => '¿Cuántos tiempos muertos tiene cada equipo en la primera y segunda parte?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial'],
                'difficulty' => 'alta',
                'option_a' => '1 en cada cuarto',
                'option_b' => '2 en primera parte y 2 en segunda parte',
                'option_c' => '2 en primera parte y 3 en segunda parte',
                'option_d' => '3 en primera parte y 2 en segunda parte',
                'correct_answer' => 'C',
                'explanation' => 'Cada equipo tiene 2 tiempos muertos en la primera parte (primeros dos cuartos) y 3 tiempos muertos en la segunda parte (últimos dos cuartos). Art. 19 Reglamento FEB.',
                'reference' => 'Art. 19 - Tiempos Muertos',
                'image_path' => null,
            ],
            [
                'question_code' => 'OFI-D-002',
                'title' => 'Falta técnica - Puntuación',
                'description' => 'Se sanciona una falta técnica. ¿Cuántos puntos se conceden?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial'],
                'difficulty' => 'alta',
                'option_a' => '1 punto',
                'option_b' => '2 puntos',
                'option_c' => '3 puntos',
                'option_d' => 'No hay puntos, solo tiros libres',
                'correct_answer' => 'A',
                'explanation' => 'Una falta técnica sancionada conlleva 1 tiro libre para el equipo contrario y posesión del balón. El tiro libre vale 1 punto. Art. 38 Reglamento FEB.',
                'reference' => 'Art. 38 - Falta Técnica',
                'image_path' => null,
            ],
            [
                'question_code' => 'OFI-D-003',
                'title' => 'Corrección de tanteo - Límite de tiempo',
                'description' => 'Se detecta un error en el tanteo de hace 3 minutos (5 puntos mal). ¿Cuándo se puede corregir?',
                'category' => 'oficial_mesa',
                'applicable_roles' => ['oficial'],
                'difficulty' => 'alta',
                'option_a' => 'Nunca, es definitivo',
                'option_b' => 'Solo con acuerdo de árbitros y entrenadores',
                'option_c' => 'Solo antes de terminar el cuarto',
                'option_d' => 'Inmediatamente sin restricciones',
                'correct_answer' => 'B',
                'explanation' => 'Los errores en el tanteo pueden corregirse si hay acuerdo entre los árbitros. Generalmente debe detectarse durante el juego. Las correcciones tardías requieren autorización de ambos árbitros. Art. 46 Reglamento FEB.',
                'reference' => 'Art. 46 - Anotador',
                'image_path' => null,
            ],

            // ===== ENTRENADORES - FÁCIL =====
            [
                'question_code' => 'ENT-F-001',
                'title' => 'Equipo de baloncesto - Jugadores',
                'description' => '¿Cuántos jugadores juegan en la cancha por equipo?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'baja',
                'option_a' => '4 jugadores',
                'option_b' => '5 jugadores',
                'option_c' => '6 jugadores',
                'option_d' => '7 jugadores',
                'correct_answer' => 'B',
                'explanation' => 'Cada equipo tiene 5 jugadores en la cancha durante el juego. El equipo puede tener más jugadores en el banquillo como suplentes.',
                'reference' => 'Art. 1 - Juego',
                'image_path' => null,
            ],
            [
                'question_code' => 'ENT-F-002',
                'title' => 'Duración de un partido',
                'description' => '¿Cuánto tiempo dura un partido de baloncesto?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'baja',
                'option_a' => '4 cuartos de 10 minutos',
                'option_b' => '4 cuartos de 12 minutos',
                'option_c' => '2 tiempos de 20 minutos',
                'option_d' => '4 cuartos de 15 minutos',
                'correct_answer' => 'B',
                'explanation' => 'Un partido de baloncesto FEB se juega en 4 cuartos de 12 minutos cada uno, con descansos de 2 minutos entre cuartos y 15 minutos en el descanso de mitad de partido. Art. 9 Reglamento FEB.',
                'reference' => 'Art. 9 - Duración del partido',
                'image_path' => null,
            ],
            [
                'question_code' => 'ENT-F-003',
                'title' => 'Sustituciones ilimitadas',
                'description' => '¿Tiene algún límite de sustituciones un entrenador durante un partido?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'baja',
                'option_a' => 'Máximo 5 sustituciones por cuarto',
                'option_b' => 'Máximo 2 sustituciones por cuarto',
                'option_c' => 'No hay límite, puede hacer sustituciones ilimitadas',
                'option_d' => 'Máximo 7 sustituciones por partido',
                'correct_answer' => 'C',
                'explanation' => 'Un entrenador puede hacer sustituciones ilimitadas durante un partido. Las sustituciones ocurren cuando el cronómetro se detiene. Art. 8 Reglamento FEB.',
                'reference' => 'Art. 8 - Equipo',
                'image_path' => null,
            ],
            [
                'question_code' => 'ENT-F-004',
                'title' => 'Composición del equipo en cancha',
                'description' => 'Según el reglamento, ¿cuál es la alineación típica en un equipo de baloncesto?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'baja',
                'option_a' => '2 bases, 2 escolta, 1 pivot',
                'option_b' => '1 base, 2 escoltas, 2 aleros, 1 pivot',
                'option_c' => '1 base, 1 escolta, 1 alero, 1 ala-pivot, 1 pivot',
                'option_d' => 'El reglamento no especifica posiciones',
                'correct_answer' => 'D',
                'explanation' => 'El reglamento FEB no especifica posiciones en el equipo. Solo requiere 5 jugadores en cancha. La estructura de posiciones es estrategia del entrenador.',
                'reference' => 'Art. 1-8 - Juego',
                'image_path' => null,
            ],

            // ===== ENTRENADORES - INTERMEDIO =====
            [
                'question_code' => 'ENT-M-001',
                'title' => 'Tácticas defensivas - Defensa zonal vs personal',
                'description' => '¿Cuándo es más efectiva una defensa zonal?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'media',
                'option_a' => 'Cuando el equipo contrario tiene buenos tiradores desde fuera',
                'option_b' => 'Cuando el equipo contrario tiene una alineación sin posiciones fijas',
                'option_c' => 'Cuando se necesita proteger la zona',
                'option_d' => 'Todas las anteriores',
                'correct_answer' => 'D',
                'explanation' => 'Una defensa zonal es efectiva en múltiples situaciones. Protege la zona, es difícil de atacar sin movimiento rápido del balón, y limita los espacios. El reglamento permite ambos tipos de defensa. Art. 35 Reglamento FEB.',
                'reference' => 'Art. 35 - Defensa',
                'image_path' => null,
            ],
            [
                'question_code' => 'ENT-M-002',
                'title' => 'Gestión del cronómetro de 24 segundos',
                'description' => 'Un entrenador necesita que el equipo contrario gaste tiempo. ¿Qué estrategia es correcta?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'media',
                'option_a' => 'Hacer presión defensiva constante',
                'option_b' => 'Permitir que el balón circule lentamente el perímetro',
                'option_c' => 'Ambas estrategias pueden ser válidas según la situación',
                'option_d' => 'Hacer fouls para detener el tiempo',
                'correct_answer' => 'C',
                'explanation' => 'La estrategia de tiempo depende del marcador. Si va atrás, requiere ritmo rápido. Si va por delante, puede ralentizar el juego. El cronómetro de 24 segundos es un factor clave. Art. 29 Reglamento FEB.',
                'reference' => 'Art. 29 - Regla de 24 segundos',
                'image_path' => null,
            ],
            [
                'question_code' => 'ENT-M-003',
                'title' => 'Uso de tiempos muertos estratégicos',
                'description' => '¿En qué situación es más importante usar un timeout?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'media',
                'option_a' => 'Cuando el equipo comienza muy mal el partido',
                'option_b' => 'Cuando se necesita frenar el ritmo ofensivo del rival',
                'option_c' => 'En el último minuto para diseñar una jugada ganadora',
                'option_d' => 'Todas las situaciones tienen igual importancia',
                'correct_answer' => 'B',
                'explanation' => 'Los tiempos muertos son herramientas estratégicas para: romper modelos ofensivos del rival, cambiar defensa, diseñar jugadas específicas, y gestionar energía. Son más efectivos cuando se usan oportunamente que al final. Art. 19 Reglamento FEB.',
                'reference' => 'Art. 19 - Tiempos Muertos',
                'image_path' => null,
            ],

            // ===== ENTRENADORES - DIFÍCIL =====
            [
                'question_code' => 'ENT-D-001',
                'title' => 'Análisis de patrones ofensivos',
                'description' => 'Un equipo muy ofensivo está ganando con una anotación rápida. ¿Cuál es la mejor estrategia defensiva?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'alta',
                'option_a' => 'Presión de medio campo constante para ralentizar',
                'option_b' => 'Defensa zonal para cerrar espacios internos',
                'option_c' => 'Presión defensiva con rotaciones rápidas',
                'option_d' => 'Combinar presión selectiva con defensas zonales y rotaciones',
                'correct_answer' => 'D',
                'explanation' => 'La defensa efectiva requiere versatilidad. Combinar presión (según timing), zonas defensivas (para proteger área) y rotaciones (para defender el perímetro) crea una defensa multidimensional. Art. 35 Reglamento FEB.',
                'reference' => 'Art. 35 - Defensa',
                'image_path' => null,
            ],
            [
                'question_code' => 'ENT-D-002',
                'title' => 'Gestión de faltas y restricciones',
                'description' => 'Un jugador clave acumula 4 faltas personales. ¿Cuál es la mejor decisión?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'alta',
                'option_a' => 'Sacarlo inmediatamente para protegerlo',
                'option_b' => 'Dejarlo en cancha jugando defensivamente muy cauteloso',
                'option_c' => 'Evaluar el partido: marcador, tiempo, rival, importancia del jugador',
                'option_d' => 'Cambiar completamente su rol defensivo',
                'correct_answer' => 'C',
                'explanation' => 'La decisión requiere análisis contextual: ¿Cuánto falta para terminar el período? ¿Van ganando o perdiendo? ¿Es un jugador clave? ¿Hay buenos suplentes? La gestión de faltas es crítica para el final del partido.',
                'reference' => 'Art. 35 - Falta Personal',
                'image_path' => null,
            ],
            [
                'question_code' => 'ENT-D-003',
                'title' => 'Estrategia de transición rápida',
                'description' => 'El equipo recupera el balón en defensa. ¿Cuál es el objetivo principal en transición?',
                'category' => 'arbitro',
                'applicable_roles' => ['entrenador'],
                'difficulty' => 'alta',
                'option_a' => 'Anotar puntos fáciles antes que el rival pueda defenderse',
                'option_b' => 'Controlar el ritmo del partido',
                'option_c' => 'Ganar el tiempo de 24 segundos',
                'option_d' => 'Ejecutar el juego ofensivo diseñado',
                'correct_answer' => 'A',
                'explanation' => 'La transición rápida busca aprovechar la ventaja numérica (menos defensores en cancha) para anotar fácilmente. El objetivo es atacar antes de que la defensa se organice, generando oportunidades de alto porcentaje. Art. 29 Reglamento FEB.',
                'reference' => 'Art. 29 - Juego',
                'image_path' => null,
            ],
        ];

        foreach ($questions as $question) {
            if (is_array($question['applicable_roles'])) {
                $question['applicable_roles'] = json_encode($question['applicable_roles']);
            }
            Question::create($question);
        }
    }
}
