<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ÁRBITRO - FALTAS
            [
                'title' => 'Falta personal - Definición',
                'description' => '¿Cuál es la definición correcta de una falta personal en baloncesto?',
                'category' => 'arbitro',
                'difficulty' => 'baja',
                'option_a' => 'Un contacto ilegal entre jugadores',
                'option_b' => 'Un movimiento ilegal sin contacto',
                'option_c' => 'Un contacto ilegal de un jugador defensor contra un atacante, o viceversa',
                'option_d' => 'Solo un contacto durante el lanzamiento',
                'correct_answer' => 'C',
                'explanation' => 'Una falta personal es el contacto ilegal entre un jugador defensivo y uno ofensivo, o entre un jugador defensivo e ilegal contra cualquier jugador. Art. 35 Reglamento FEB.',
                'reference' => 'Art. 35 - Falta Personal',
            ],
            [
                'title' => 'Regla de los tres segundos',
                'description' => 'Un jugador está en la zona restringida más de 3 segundos consecutivos sin que el equipo tenga la posesión del balón. ¿Es falta ofensiva?',
                'category' => 'arbitro',
                'difficulty' => 'media',
                'option_a' => 'Sí, siempre es una infracción ofensiva',
                'option_b' => 'No, solo es infracción si el equipo está atacando',
                'option_c' => 'No, la regla de 3 segundos solo se aplica al equipo con balón',
                'option_d' => 'Sí, salvo que esté marcando a un jugador ofensivo',
                'correct_answer' => 'C',
                'explanation' => 'Un jugador ofensivo puede estar en la zona restringida más de 3 segundos si no tiene la posesión del balón y está dentro de ella. La regla de 3 segundos se aplica al jugador o los jugadores del equipo que tiene la posesión. Art. 26.3 Reglamento FEB.',
                'reference' => 'Art. 26.3 - Regla de 3 segundos',
            ],
            [
                'title' => 'Viajada - Movimiento de pies',
                'description' => 'Un jugador recibe el balón con ambos pies en el aire. ¿Cuál es el procedimiento correcto?',
                'category' => 'arbitro',
                'difficulty' => 'media',
                'option_a' => 'Puede apoyar ambos pies simultáneamente',
                'option_b' => 'Solo puede apoyar uno de los pies',
                'option_c' => 'No puede tocar el suelo con los pies',
                'option_d' => 'Debe regresar donde saltó',
                'correct_answer' => 'A',
                'explanation' => 'Un jugador que recibe el balón en el aire puede apoyar ambos pies simultáneamente. Esto establece su posición y ambos se consideran pies de pivote. Art. 24.2 Reglamento FEB.',
                'reference' => 'Art. 24.2 - Viajada',
            ],
            [
                'title' => 'Dobles - Bote de balón',
                'description' => 'Un jugador bota el balón, lo controla con ambas manos simultáneamente y luego lo bota de nuevo. ¿Es una infracción?',
                'category' => 'arbitro',
                'difficulty' => 'alta',
                'option_a' => 'No, puede controlar el balón con ambas manos mientras lo está botando',
                'option_b' => 'Sí, es un doble inmediato',
                'option_c' => 'Solo si lanza después',
                'option_d' => 'No, porque el contacto es simultáneo',
                'correct_answer' => 'B',
                'explanation' => 'Una vez que un jugador ha botado el balón, no puede volver a botarlo si previamente lo ha controlado con ambas manos simultáneamente. Esto constituye un doble. Art. 25.2 Reglamento FEB.',
                'reference' => 'Art. 25.2 - Dobles',
            ],
            [
                'title' => 'Defensa activa - Zona',
                'description' => 'En defensa de zona 2-3, un defensor está dentro de la zona restringida sin marcar a ningún atacante. ¿Es permitido?',
                'category' => 'arbitro',
                'difficulty' => 'media',
                'option_a' => 'No, es una infracción de zona inmediata',
                'option_b' => 'Sí, siempre que esté dentro de la zona restricción',
                'option_c' => 'Solo si está en una posición defensiva activa',
                'option_d' => 'No, debe estar marcando siempre',
                'correct_answer' => 'C',
                'explanation' => 'En defensa de zona, un defensor puede estar en la zona restricción sin marcar directamente a un atacante, siempre que esté en una posición defensiva activa (brazos levantados, posición defensiva, etc.). Art. 26.1 Reglamento FEB.',
                'reference' => 'Art. 26.1 - Posición defensiva en zona',
            ],
            [
                'title' => 'Pasos con pivote',
                'description' => 'Un jugador establece su pie pivote y da dos pasos más un bote. ¿Es correcto?',
                'category' => 'arbitro',
                'difficulty' => 'media',
                'option_a' => 'No, solo puede dar dos pasos en total',
                'option_b' => 'Sí, después de pivotar puede botar',
                'option_c' => 'No, si bota debe hacerlo antes del primer paso',
                'option_d' => 'Sí, sin límite de pasos si bota al final',
                'correct_answer' => 'B',
                'explanation' => 'Un jugador puede establecer un pie pivote, dar dos pasos y luego realizar un bote. El bote puede ocurrir después de los pasos. Art. 24.3 Reglamento FEB.',
                'reference' => 'Art. 24.3 - Pasos y pivote',
            ],
            // ÁRBITRO - FALTAS TÉCNICAS
            [
                'title' => 'Falta técnica - Reclamación',
                'description' => 'Un entrenador discute respetuosamente una decisión del árbitro. ¿Es falta técnica?',
                'category' => 'arbitro',
                'difficulty' => 'media',
                'option_a' => 'No, puede reclamar una decisión',
                'option_b' => 'Sí, cualquier reclamación es técnica',
                'option_c' => 'Solo si es agresivo',
                'option_d' => 'Depende del árbitro',
                'correct_answer' => 'A',
                'explanation' => 'Los entrenadores pueden solicitar una aclaración de una decisión del árbitro de manera respetuosa. La falta técnica se sanciona cuando la conducta es abusiva, desafiante o irrespetuosa. Art. 38 Reglamento FEB.',
                'reference' => 'Art. 38 - Falta Técnica',
            ],
            [
                'title' => 'Falta flagrante - Peligrosidad',
                'description' => 'Un defensor golpea el balón hacia la cara del atacante pero hace contacto. ¿Es falta flagrante?',
                'category' => 'arbitro',
                'difficulty' => 'alta',
                'option_a' => 'No, fue intencional ir al balón',
                'option_b' => 'Sí, siempre es flagrante si hay contacto',
                'option_c' => 'Sí, porque hace contacto con el cuerpo de manera peligrosa',
                'option_d' => 'No, si fue un intento de defensa',
                'correct_answer' => 'C',
                'explanation' => 'Una falta flagrante es aquella donde el contacto es peligroso para la integridad del rival. Si existe contacto al ir por el balón que resulta peligroso, puede ser falta flagrante. Art. 36.2 Reglamento FEB.',
                'reference' => 'Art. 36.2 - Falta Flagrante',
            ],
            // OFICIAL DE MESA - ANOTACIÓN
            [
                'title' => 'Canasta válida - Contacto con aro',
                'description' => 'El balón pasa a través del aro pero antes de salir de la canasta, un jugador toca el aro o la red. ¿Es canasta válida?',
                'category' => 'oficial_mesa',
                'difficulty' => 'alta',
                'option_a' => 'Sí, siempre que haya pasado el aro',
                'option_b' => 'No, cualquier contacto invalida la canasta',
                'option_c' => 'No, es interferencia de balón en canasta',
                'option_d' => 'Sí, solo si el contacto es involuntario',
                'correct_answer' => 'C',
                'explanation' => 'Si el balón ha pasado completamente a través de la canasta desde arriba y es tocado antes de salir, es interferencia de balón en canasta y no es válida. Art. 31.2 Reglamento FEB.',
                'reference' => 'Art. 31.2 - Interferencia de balón en canasta',
            ],
            [
                'title' => 'Puntuación - Faltas sancionadas',
                'description' => '¿Cuántos puntos se conceden por una falta técnica sancionada con tiros libres?',
                'category' => 'oficial_mesa',
                'difficulty' => 'media',
                'option_a' => '1 punto',
                'option_b' => '2 puntos',
                'option_c' => '3 puntos',
                'option_d' => 'Ninguno, solo tiros libres',
                'correct_answer' => 'A',
                'explanation' => 'Una falta técnica sancionada por el árbitro conlleva un tiro libre (1 punto) para el equipo contrario y posesión de balón. Art. 38 Reglamento FEB.',
                'reference' => 'Art. 38 - Falta Técnica',
            ],
            [
                'title' => 'Registro de faltas personales',
                'description' => 'Un jugador recibe su 5ª falta personal. ¿Debe el anotador comunicar algo especial?',
                'category' => 'oficial_mesa',
                'difficulty' => 'baja',
                'option_a' => 'No, es responsabilidad del árbitro',
                'option_b' => 'Sí, debe avisar que tiene 5 faltas',
                'option_c' => 'Sí, debe sonar una alarma inmediata',
                'option_d' => 'Sí, debe mostrar una tarjeta roja',
                'correct_answer' => 'B',
                'explanation' => 'El anotador debe comunicar al árbitro cuando un jugador ha cometido 5 faltas personales para que sepa que se retira del juego. Art. 46.3 Reglamento FEB.',
                'reference' => 'Art. 46.3 - Responsabilidades del anotador',
            ],
            [
                'title' => 'Tanteo - Corrección de errores',
                'description' => 'Se detecta un error en el tanteo que ocurrió hace 2 minutos (5 puntos mal registrados). ¿Cuándo se puede corregir?',
                'category' => 'oficial_mesa',
                'difficulty' => 'media',
                'option_a' => 'Nunca, es definitivo',
                'option_b' => 'Solo si ambos árbitros y entrenadores lo autorizan',
                'option_c' => 'Solo antes de que termine el período',
                'option_d' => 'Inmediatamente sin importar el tiempo',
                'correct_answer' => 'B',
                'explanation' => 'Los errores en el tanteo pueden corregirse si el árbitro lo autoriza, pero generalmente debe haber acuerdo de ambos árbitros. Si se detecta durante el juego, se avisa inmediatamente. Art. 46 Reglamento FEB.',
                'reference' => 'Art. 46 - Anotador',
            ],
            // OFICIAL DE MESA - CRONOMETRAJE
            [
                'title' => 'Regla de 24 segundos - Reset',
                'description' => 'Un equipo pierde la posesión por falta ofensiva. ¿Cómo se resetea el cronómetro de 24 segundos?',
                'category' => 'oficial_mesa',
                'difficulty' => 'media',
                'option_a' => 'Se resetea a 24 segundos para el nuevo equipo',
                'option_b' => 'Se resetea a 14 segundos (resto del anterior)',
                'option_c' => 'Continúa desde donde estaba',
                'option_d' => 'Se detiene indefinidamente',
                'correct_answer' => 'A',
                'explanation' => 'Cuando cambia la posesión, el cronómetro de 24 segundos se resetea a 24 segundos completos para el nuevo equipo en posesión. Art. 29.1 Reglamento FEB.',
                'reference' => 'Art. 29.1 - Regla de 24 segundos',
            ],
            [
                'title' => 'Tiempo muerto - Duración',
                'description' => '¿Cuánto tiempo dura un tiempo muerto regular solicitado por un equipo en el reglamento FEB?',
                'category' => 'oficial_mesa',
                'difficulty' => 'baja',
                'option_a' => '30 segundos',
                'option_b' => '1 minuto (60 segundos)',
                'option_c' => '45 segundos',
                'option_d' => '90 segundos',
                'correct_answer' => 'B',
                'explanation' => 'Un tiempo muerto regular o timeout dura 60 segundos según el Reglamento FEB. Art. 19 Reglamento FEB.',
                'reference' => 'Art. 19 - Tiempo Muerto',
            ],
            [
                'title' => 'Violación de regla de 8 segundos',
                'description' => 'El cronometrador marca 8 segundos en la regla de medio campo. ¿Qué hace el anotador/cronometrador?',
                'category' => 'oficial_mesa',
                'difficulty' => 'media',
                'option_a' => 'Hace sonar la bocina sin parar el juego',
                'option_b' => 'Solo lo registra sin hacer nada',
                'option_c' => 'Avisa al árbitro levantando la mano',
                'option_d' => 'Pausa el cronómetro',
                'correct_answer' => 'A',
                'explanation' => 'El cronometrador hace sonar la bocina/alarma para indicar que se han completado 8 segundos sin que el equipo cruce la línea de medio campo. Art. 28 Reglamento FEB.',
                'reference' => 'Art. 28 - Regla de 8 segundos',
            ],
            // OFICIAL DE MESA - ESTADÍSTICAS Y CONTROL
            [
                'title' => 'Faltas de equipo por período',
                'description' => 'En un período, un equipo comete 7 faltas personales. ¿Qué sucede?',
                'category' => 'oficial_mesa',
                'difficulty' => 'media',
                'option_a' => 'No pasa nada especial, se juega normalmente',
                'option_b' => 'La 4ª falta comienza a generar tiros libres adicionales',
                'option_c' => 'Después de la 5ª falta se le concede posesión alternativa',
                'option_d' => 'El equipo es descalificado',
                'correct_answer' => 'B',
                'explanation' => 'Cuando un equipo comete 4 o más faltas personales en un período, cualquier falta adicional del equipo sancionada con tiros libres conlleva 2 tiros libres (excepto si es falta de tiro de 3 puntos, que sigue siendo 3 tiros). Art. 37 Reglamento FEB.',
                'reference' => 'Art. 37 - Faltas de equipo',
            ],
            [
                'title' => 'Fouls personales del árbitro',
                'description' => 'Un árbitro comete un error grave en la interpretación de una regla. ¿Cuál es la responsabilidad del anotador?',
                'category' => 'oficial_mesa',
                'difficulty' => 'alta',
                'option_a' => 'Debe corregir inmediatamente el error',
                'option_b' => 'Debe informar solo si se lo pide el entrenador',
                'option_c' => 'Debe estar atento y comunicar si lo detecta',
                'option_d' => 'No tiene ninguna responsabilidad',
                'correct_answer' => 'C',
                'explanation' => 'El anotador/oficial de mesa debe asistir a los árbitros en situaciones donde pueda haber ocurrido un error. Si detecta algo que afecte el registro correcto del juego, debe comunicarlo. Art. 46 Reglamento FEB.',
                'reference' => 'Art. 46 - Responsabilidades de la mesa',
            ],
            // ÁRBITRO - REGLAS DE JUEGO
            [
                'title' => 'Saque de banda',
                'description' => 'En un saque de banda, el jugador que saca ¿puede pisar la línea?',
                'category' => 'arbitro',
                'difficulty' => 'baja',
                'option_a' => 'No, debe estar completamente fuera de la cancha',
                'option_b' => 'Sí, puede tener un pie en la línea',
                'option_c' => 'Sí, puede pisar la línea con ambos pies',
                'option_d' => 'Solo en saques defensivos',
                'correct_answer' => 'A',
                'explanation' => 'El jugador que realiza un saque debe estar completamente fuera de la cancha. El balón debe ser pasado desde un punto en la línea de fondo o lateral. Art. 8.1 Reglamento FEB.',
                'reference' => 'Art. 8.1 - Saque',
            ],
            [
                'title' => 'Portero - Línea de medio campo',
                'description' => 'Un jugador recibe el balón de su portero en el aire y cruza la línea de medio campo aún en el aire. ¿Comete violación de retaguardia?',
                'category' => 'arbitro',
                'difficulty' => 'media',
                'option_a' => 'Sí, siempre viola si la bola cruza la línea',
                'option_b' => 'No, porque recibió de su portero',
                'option_c' => 'No, porque estaba en el aire',
                'option_d' => 'Sí, pero solo si cae después de la línea',
                'correct_answer' => 'C',
                'explanation' => 'Un jugador que está en el aire cuando cruza la línea de medio campo no comete violación de retaguardia. Lo importante es dónde pisa después de cruzar la línea. Art. 30.1 Reglamento FEB.',
                'reference' => 'Art. 30.1 - Violación de retaguardia',
            ],
            [
                'title' => 'Lanzamiento de 3 puntos - Posición correcta',
                'description' => 'Un jugador está exactamente en la línea de 3 puntos cuando lanza. ¿Cuántos puntos anota si mete?',
                'category' => 'arbitro',
                'difficulty' => 'baja',
                'option_a' => '2 puntos',
                'option_b' => '3 puntos',
                'option_c' => 'Depende de si el pie está dentro o fuera',
                'option_d' => '1 punto',
                'correct_answer' => 'A',
                'explanation' => 'Para anotar un lanzamiento de 3 puntos, el jugador debe estar completamente detrás de la línea de 3 puntos cuando realiza el lanzamiento. Si está en la línea o dentro, son 2 puntos. Art. 23.2 Reglamento FEB.',
                'reference' => 'Art. 23.2 - Lanzamiento de 3 puntos',
            ],
            [
                'title' => 'Bloqueo e interferencia',
                'description' => 'Un defensor toca el balón cuando está en la trayectoria descendente hacia la canasta, pero aún está subiendo. ¿Es interferencia?',
                'category' => 'arbitro',
                'difficulty' => 'alta',
                'option_a' => 'Sí, es interferencia siempre',
                'option_b' => 'No, es un bloqueo permitido',
                'option_c' => 'No, porque el balón está subiendo',
                'option_d' => 'Sí, pero solo en tiros libres',
                'correct_answer' => 'C',
                'explanation' => 'La interferencia de balón en canasta solo ocurre cuando el balón está en trayectoria descendente hacia la canasta. Si el balón está subiendo o en su fase ascendente, es un bloqueo legal. Art. 31.2 Reglamento FEB.',
                'reference' => 'Art. 31.2 - Interferencia de balón',
            ],
            [
                'title' => 'Falta antideportiva',
                'description' => 'Un defensor comete una falta a propósito para detener un contraataque rápido del equipo rival. ¿Qué tipo de falta es?',
                'category' => 'arbitro',
                'difficulty' => 'media',
                'option_a' => 'Falta personal normal',
                'option_b' => 'Falta antideportiva',
                'option_c' => 'Falta flagrante',
                'option_d' => 'Falta técnica',
                'correct_answer' => 'B',
                'explanation' => 'Una falta cometida deliberadamente fuera del juego normal (como detener un contraataque) es una falta antideportiva. El equipo contrario obtiene tiros libres y posesión. Art. 37.2 Reglamento FEB.',
                'reference' => 'Art. 37.2 - Falta Antideportiva',
            ],
        ];

        foreach ($questions as $question) {
            $question['image_path'] = null;
            $question['is_active'] = true;
            Question::create($question);
        }
    }
}
